version: "3.7"
networks: 
  dockerrize_network:
    driver: bridge
services:
  phpfpm:
    build:
      context: ./phpfpm
      dockerfile: Dockerfile
    # ports:
    #   - "9000:9000"
    container_name: dockerize_php_phpfpm
    working_dir: /var/www/myapp
    networks: 
      - dockerrize_network
    volumes: 
      - "./src:/var/www/myapp"
  phpcli:
    build:
      context: ./phpcli
      dockerfile: Dockerfile
    # ports:
    #   - "9000:9000"
    container_name: dockerize_php_cli
    working_dir: /var/www/myapp
    networks: 
      - dockerrize_network
    volumes: 
      - "./src:/var/www/myapp"
  web:
    depends_on: 
      - mariadb
    image: nginx:latest
    ports:
      - "8081:80"
    working_dir: /var/www/myapp
    networks: 
      - dockerrize_network
    volumes: 
      - "./src:/var/www/myapp"
      - "./docker/:/etc/nginx/conf.d/"
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes: 
      - "./data:/var/lib/mysql"
    networks: 
      - dockerrize_network
  redis:
    image: redis
    volumes: 
      - "./cache:/data"
    restart: always
    networks: 
      - dockerrize_network
    ports:
      - "6379:6379"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080"
    networks: 
      - dockerrize_network